In [2]:
import pandas as pd

#Q1. Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the dataset information to understand its structure.

df = pd.read_csv(r"C:\Users\ABHISHEK\OneDrive\Desktop\Hrushikesh\PW SKILLS ASSIGNMENTS\Python\retail_dataset .csv")
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    str
 1   Customer ID       100 non-null    str
 2   Product Category  97 non-null     str
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    str
 6   Region            98 non-null     str
dtypes: float64(2), str(5)
memory usage: 5.6 KB

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

In [13]:
#Q2. Inspect the dataset and identify missing values in each column. Display the total number of missing values present in the dataset.
missing_per_column = df.isnull().sum()
print(missing_per_column)

df.isnull().sum().sum()

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

np.int64(12)

In [17]:
#Q3. Replace missing values in the Quantity and Price columns with their respective mean values using Pandas.
df.Quantity.value_counts()
df.Price.value_counts()
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())
df['Price'] = df['Price'].fillna(df['Price'].mean())
df.isnull().sum()

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            0
Price               0
Date                0
Region              2
dtype: int64

In [20]:
#Q4. Remove all rows where the Product Category or Region column contains missing values.
df = df.dropna(subset=['Product Category', 'Region'])
df.isnull().sum()

Transaction ID      0
Customer ID         0
Product Category    0
Quantity            0
Price               0
Date                0
Region              0
dtype: int64

In [22]:
import numpy as np

#Q5. Create a new column called Revenue using NumPy, where:Revenue = Quantity × Price ,Display the updated dataset with the new column.
df['Revenue'] = np.multiply(df['Quantity'], df['Price'])
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0

In [29]:
#Q6. Using NumPy, calculate the total revenue generated from all transactions in the dataset
total_revenue=np.sum(df['Revenue'].values)
print(total_revenue)

465529.66058002145

In [31]:
#Q7. Group the dataset by Product Category and calculate the total revenue generated by each category
df.groupby('Product Category')['Revenue'].sum()

Product Category
Beauty          27647.000000
Books           29597.938776
Clothing        85006.000000
Electronics     93204.315789
Furniture      129664.526316
Groceries       11978.000000
Sports          34484.000000
Toys            53947.879699
Name: Revenue, dtype: float64

In [45]:
#Q8. Based on the revenue calculated for each product category, identify the top 3 categories with the highest revenue and the bottom 3 categories with the lowest revenue.
highest_revenue= df.groupby('Product Category')['Revenue'].sum().nlargest(3)
print(highest_revenue)

lowest_revenue=df.groupby('Product Category')['Revenue'].sum().sort_values(ascending=True).head(3)
print(lowest_revenue)

Product Category
Furniture      129664.526316
Electronics     93204.315789
Clothing        85006.000000
Name: Revenue, dtype: float64
Product Category
Groceries    11978.000000
Beauty       27647.000000
Books        29597.938776
Name: Revenue, dtype: float64

In [55]:
#Q9. Group the dataset by Region and calculate the total revenue generated in each region. Identify the region with the highest revenue and the region with the lowest revenue.
total_revenue_region=df.groupby('Region')['Revenue'].sum()
print(total_revenue_region)
highest_value_region=total_revenue_region.idxmax()
highest_revenue_region= total_revenue_region.max()
print("highest_revenue_region",highest_value_region,"-",highest_revenue_region)

lowest_value_region= total_revenue_region.idxmin()
lowest_revenue_region= total_revenue_region.min()
print("lowest_revenue_region",lowest_value_region,"-",lowest_revenue_region)

Region
East     126232.044039
North    153244.353383
South    104855.736842
West      81197.526316
Name: Revenue, dtype: float64
highest_revenue_region North - 153244.35338345866
lowest_revenue_region West - 81197.52631578947

In [61]:
#Q10. Extract the month from the Date column using Pandas and group the dataset by month to calculate thetotal monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column using NumPy.
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df['Month'] = df['Date'].dt.month
monthly_revenue = df.groupby('Month')['Revenue'].sum()
print("Monthly Revenue:", monthly_revenue)
mean_revenue = np.mean(df['Revenue'])
median_revenue = np.median(df['Revenue'])
std_revenue = np.std(df['Revenue'])
print("Mean Revenue:", mean_revenue)
print("Median Revenue:", median_revenue)
print("Standard Deviation of Revenue:", std_revenue)

Monthly Revenue: Month
1.0      2240.000000
2.0     13945.000000
3.0      3220.000000
4.0      9146.105263
5.0      5355.000000
6.0     16400.000000
7.0     24083.938776
8.0     34491.000000
9.0     16479.210526
10.0    39939.142857
11.0    11747.000000
12.0    13072.736842
Name: Revenue, dtype: float64
Mean Revenue: 4900.312216631804
Median Revenue: 3282.1052631578946
Standard Deviation of Revenue: 4721.171795257337